version: '3'

services:
  db:
    image: mariadb
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: raksonme
      MYSQL_DATABASE: swiftly_store
    networks:
      - swiftly-network

  spring:
    image: raks/spring
    container_name: spring-container
    build:
      context: ./spring
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - swiftly-network

  vue:
    image: raks/vue
    container_name: vue-container
    build:
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - spring
    networks:
      - swiftly-network

networks:
  swiftly-network:
    driver: bridge