object Versions {
    const val ANDROID_GRADLE            = "7.3.0"
    const val ANDROIDX_ACTIVITY         = "1.7.0"
    const val ANDROIDX_APPCOMPAT        = "1.6.1"
    const val ANDROIDX_CONSTRAINTLAYOUT = "2.1.4"
    const val ANDROIDX_CORE             = "1.9.0"
    const val ANDROIDX_LIFECYCLE        = "2.6.1"
    const val ANDROIDX_ROOM             = "2.5.1"
    const val ANDROIDX_TEST_ESPRESSO    = "3.5.1"
    const val ANDROIDX_TEST_EXT         = "1.1.5"
    const val ANDROIDX_VIEWMODEL        = "2.6.1"
    const val HILT                      = "2.45"
    const val JUNIT                     = "4.13.2"
    const val KOTLIN                    = "1.8.0"
    const val MATERIAL                  = "1.8.0"
}